from django.db import models

# Create your models here.

class Ocorrencia(models.Model):
	codigo_ocorrencia = models.IntegerField(primary_key=True)
	classificacao = models.CharField(max_length=30)
	tipo = models.CharField(max_length=80)
	localidade = models.CharField(max_length=100)
	uf = models.CharField(max_length=3)
	pais = models.CharField(max_length=80)
	aerodromo = models.CharField(max_length=4, null=True, blank=True, default=None)
	dia_ocorrencia = models.DateField()
	horario_utc = models.TimeField()
	sera_investigada = models.CharField(max_length=5, null=True, blank=True, default=None)
	comando_investigador = models.CharField(max_length=15)
	status_investigacao = models.CharField(max_length=10, null=True, blank=True, default=None)
	numero_relatorio = models.CharField(max_length=150, null=True, blank=True, default=None)
	relatorio_publicado = models.CharField(max_length=5, null=True, blank=True, default=None)
	dia_publicacao = models.DateField(null=True, blank=True, default=None)
	quantidade_recomendacoes = models.IntegerField(default=0)
	aeronaves_envolvidas = models.IntegerField()
	saida_pista = models.IntegerField(null=True, blank=True, default=None)
	dia_extracao = models.DateField()


class Aeronave(models.Model):
	codigo_aeronave = models.IntegerField(primary_key=True)
	codigo_ocorrencia = models.ForeignKey(Ocorrencia)
	matricula = models.CharField(max_length=10)
	codigo_operador = models.IntegerField()
	equipamento = models.CharField(max_length=45)
	fabricante = models.CharField(max_length=45)
	modelo = models.CharField(max_length=45)
	tipo_motor = models.CharField(max_length=45)
	quantidade_motores = models.IntegerField(default=0)
	peso_maximo_decolagem = models.FloatField()
	quantidade_assentos = models.IntegerField(default=0)
	ano_fabricacao = models.IntegerField(default=0)
	pais_registro = models.CharField(max_length=80)
	categoria_registro = models.CharField(max_length=6)
	categoria_aviacao = models.CharField(max_length=50)
	origem_voo = models.CharField(max_length=5, null=True, blank=True, default=None)
	destino_voo = models.CharField(max_length=5, null=True, blank=True, default=None)
	fase_operacao = models.CharField(max_length=100)
	tipo_operacao = models.CharField(max_length=30)
	nivel_dano = models.CharField(max_length=30, null=True, blank=True, default=None)
	quantidade_fatalidades = models.IntegerField(default=0)
	dia_extracao = models.DateField()


class FatorContribuinte(models.Model):
	codigo_fator = models.IntegerField(primary_key=True)
	codigo_ocorrencia = models.ForeignKey(Ocorrencia)
	fator = models.CharField(max_length=80)
	aspecto = models.CharField(max_length=40, null=True, blank=True, default=None)
	condicionante = models.CharField(max_length=40, null=True, blank=True, default=None)
	area = models.CharField(max_length=15, null=True, blank=True, default=None)	
	detalhe_fator = models.CharField(max_length=100, null=True, blank=True, default=None)
	dia_extracao = models.DateField()
